### ISSUE TITLE
adding to vcpkg

### ISSUE THREAD

**Issue by jfnaugusto** [zlib-ng/minizip-ng#540]
Hi,

Any chance of adding this minzip rewrite to vcpkg
https://github.com/microsoft/vcpkg/blob/master/docs/examples/packaging-github-repos.md

Thanks.

**Comment by prateek9623** [comment]
I am working on this, but we require some changes to differentiate this library from original minizip lib. So I have a question, should we make this changes:

```cmake
    write_basic_package_version_file(${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config-version.cmake
        COMPATIBILITY SameMajorVersion)
    set(MINIZIP_CONFIG_CONTENT "@PACKAGE_INIT@\n")
    if(MINIZIP_DEP_PKG)
        string(APPEND MINIZIP_CONFIG_CONTENT "include(CMakeFindDependencyMacro)\n")
        foreach(PKG_NAME ${MINIZIP_DEP_PKG})
            string(APPEND MINIZIP_CONFIG_CONTENT "find_dependency(${PKG_NAME} REQUIRED)\n")
        endforeach()
    endif()
    string(APPEND MINIZIP_CONFIG_CONTENT "include(\"\${CMAKE_CURRENT_LIST_DIR}/${PROJECT_NAME}.cmake\")")
    file(WRITE minizip-config.cmake.in ${MINIZIP_CONFIG_CONTENT})

    # Create config for find_package()
    configure_package_config_file(minizip-config.cmake.in ${PROJECT_NAME}-config.cmake
        INSTALL_DESTINATION "${INSTALL_CMAKE_DIR}")

    file(REMOVE minizip-config.cmake.in)

    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config-version.cmake
                  ${CMAKE_CURRENT_BINARY_DIR}/${PROJECT_NAME}-config.cmake
            DESTINATION "${INSTALL_CMAKE_DIR}")
``` 

this would create config files with respect to project name with suffix, so for e.g.:
if suffix is "-ng". It will create files:

- minizip-ng-config-verrsion.cmake
- minizip-ng-config.cmake
- minizip-ng-config-(debug/release).cmake
- minizip-ng.cmake

and while using lib:

```cmake
find_package(minizip-ng REQUIRED)
target_link_libraries(main PRIVATE MINIZIP::minizip-ng)

```

**Comment by prateek9623** [comment]
@nmoinvaz any comment on this?

**Comment by nmoinvaz** [comment]
Yes those changes seem appropriate.

**Comment by prateek9623** [comment]
@nmoinvaz  I have created a pull request in vcpkg to support this, can you check it out?
https://github.com/microsoft/vcpkg/pull/17101

**Comment by nmoinvaz** [comment]
Looks like this was merged. Nice!

**Comment by apteryks** [comment]
@prateek9623 What are the added `find_dependency` calls useful for? It breaks using minizip-ng in a library that doesn't have these in its environment, as `find_dependency` returns early if it fails finding the dep, e.g. xlsxio in a pure environment having a toolchain with core utilities and the following direct inputs:`expat minizip-ng pkg-config which`:
```
CMake Error at /gnu/store/nj8b56k44g08rji2pah1356y5pz198iv-cmake-minimal-3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  /gnu/store/nj8b56k44g08rji2pah1356y5pz198iv-cmake-minimal-3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /gnu/store/nj8b56k44g08rji2pah1356y5pz198iv-cmake-minimal-3.24.2/share/cmake-3.24/Modules/FindZLIB.cmake:166 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  /gnu/store/nj8b56k44g08rji2pah1356y5pz198iv-cmake-minimal-3.24.2/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /gnu/store/az3lg91ijmn6wnac29xxvrqh6qi8iprf-minizip-ng-4.0.10-0.636cba8/lib/cmake/minizip-ng/minizip-ng-config.cmake:27 (find_dependency)
  CMakeLists.txt:55 (FIND_PACKAGE)
```

So, to be able to use minizip-ng in any cmake project, one is forced to propagate all of these dependencies, which serves no purpose as `minizip-ng.cmake` doesn't make use of their targets.

**Comment by apteryks** [comment]
Also, see the note about `find_dependency` at https://cmake.org/cmake/help/v4.1/module/CMakeFindDependencyMacro.html:
> The call to [return()](https://cmake.org/cmake/help/v4.1/command/return.html#command:return) makes this macro unsuitable to call from [Find Modules](https://cmake.org/cmake/help/v4.1/manual/cmake-developer.7.html#find-modules).
