### ISSUE TITLE
mz_crypt_openssl.c uses deprecated API

### ISSUE THREAD

**Issue by Nekto89** [zlib-ng/minizip-ng#546]
minizip can't be linked with OpenSSL 1.1.0+ that was built with no-deprecated option.

Example of error with OpenSSL 1.1.1g:
```
9>libminizip.lib(mz_crypt_openssl.obj) : error LNK2001: unresolved external symbol ERR_load_crypto_strings
9>libminizip.lib(mz_crypt_openssl.obj) : error LNK2001: unresolved external symbol OpenSSL_add_all_algorithms
```

**Comment by nmoinvaz** [comment]
Can you make a pull request?

**Comment by Nekto89** [comment]
I'm not familiar enough with OpenSSL. It's not clear for me from documentation whether implicit initialization is needed at all for 1.1.0+. They can be hidden under `#if OPENSSL_VERSION_NUMBER < 0x10100000L` if they aren't needed

**Comment by nmoinvaz** [comment]
How are you compiling minizip?

**Comment by Nekto89** [comment]
I have complex package management based on top of ExternalProject from CMake.

But to reproduce this issue, it is enough to just build openssl and pass it to minizip configuration.

For example, with installed Conan:

```
cmake_minimum_required(VERSION 3.0.2)

# Download automatically, you can also just copy the conan.cmake file
if(NOT EXISTS "${CMAKE_BINARY_DIR}/conan.cmake")
   message(STATUS "Downloading conan.cmake from https://github.com/conan-io/cmake-conan")
   file(DOWNLOAD "https://raw.githubusercontent.com/conan-io/cmake-conan/master/conan.cmake"
                  "${CMAKE_BINARY_DIR}/conan.cmake")
endif()

set(CMAKE_CONFIGURATION_TYPES Release)
set(CMAKE_BUILD_TYPE Release)
set(BUILD_SHARED_LIBS ON)

include(${CMAKE_BINARY_DIR}/conan.cmake)

conan_cmake_run(REQUIRES openssl/1.1.1i
                OPTIONS openssl:shared=False
                        openssl:no_deprecated=True
                BASIC_SETUP CMAKE_TARGETS
                BUILD missing)

set(MZ_OPENSSL ON CACHE BOOL "Enables OpenSSL for encryption")

add_subdirectory(minizip)
```
 With this approach there is also error because minizip doesn't use cmake targets that are created by call to find_package, but it can be ignored for this issue.

**Comment by nmoinvaz** [comment]
This should be resolved now in the develop branch.
