### ISSUE TITLE
how to use minizip with Cmake's find_package in windows

### ISSUE THREAD

**Issue by prateek9623** [zlib-ng/minizip-ng#550]
What is the target name which is to be linked .

**Comment by nmoinvaz** [comment]
libminizip.

**Comment by nmoinvaz** [comment]
I'm not sure. Perhaps libminizip?

**Comment by prateek9623** [comment]
thats just the lib name, it doesn't provide libminizip properties like include dir or target dependency

**Comment by prateek9623** [comment]
it can be fixed by appending "include("${CMAKE_CURRENT_LIST_DIR}/minizip.cmake")" in minizip-config.cmake.in

**Comment by prateek9623** [comment]
also, 1 suggestion minizip-config.cmake.in should have CMake's "find_dependeny" function call for the dependency of minizip, this will check if dependant libs are present in the system or not.

**Comment by prateek9623** [comment]
pull request: https://github.com/zlib-ng/minizip-ng/pull/551
