### ISSUE TITLE
variable "ZSTD_LIBRARIES" is not getting set in cmake

### ISSUE THREAD

**Issue by prateek9623** [zlib-ng/minizip-ng#552]
I was trying to create the port file for minizip in vcpkg. But while building it was failing.
Note: vcpkg by default create's the shared library in windows
So, I looked in logs and found out that zstd was not used while linking. After further looking and debugging CMakelist.txt I found out variable ZSTD_LIBRARIES was not being set.

**Comment by nmoinvaz** [comment]
Feel free to create PR to fix it.

**Comment by prateek9623** [comment]
ok am working on it, but I wanted to ask what is cmake minimum is ok to use

**Comment by nmoinvaz** [comment]
It looks like #553 suggests at least 3.13.

**Comment by prateek9623** [comment]
ok i will add that to0

**Comment by prateek9623** [comment]
PR: https://github.com/zlib-ng/minizip-ng/pull/554

**Comment by nmoinvaz** [comment]
Should be in `dev` branch.
