### ISSUE TITLE
Incorrect cmake_minimum_required

### ISSUE THREAD

**Issue by Nekto89** [zlib-ng/minizip-ng#553]
https://github.com/zlib-ng/minizip-ng/blob/6f17da582d2327c8cdc43622ddd31a185b6ef5fb/CMakeLists.txt#L8
https://github.com/zlib-ng/minizip-ng/blob/6f17da582d2327c8cdc43622ddd31a185b6ef5fb/CMakeLists.txt#L702

target_link_directories was added in 3.13
https://cmake.org/cmake/help/latest/release/3.13.html?highlight=target_link_directories#commands

**Comment by nmoinvaz** [comment]
Feel free to create PR to fix it.

**Comment by prateek9623** [comment]
fixed int #554

**Comment by nmoinvaz** [comment]
Should be fixed in `dev` branch now.
