### ISSUE TITLE
How to link Bzip and Zstd directories to Cmake on Windows ?

### ISSUE THREAD

**Issue by MacButters** [zlib-ng/minizip-ng#559]
Hi, 
I need to develop a small dll that uses minizip on Windows to make a nuget for Visual Studio.
 and I can't fetch the libraries during the building. 
For lzma and zlib there was no problem using the Cmake variables Lib_Include and Lib_Library, but I didnt find such variables for Bzip2 and zstd. Is there a way to link the library directories using Cmake ?

Thank you

**Comment by nmoinvaz** [comment]
There have been some changes surrounding this in the `dev` branch? Have you tried it?

**Comment by MacButters** [comment]
With Mz_Fetch on, I did find corresponding variables in the CMakeCache file. Using these I managed to link correctly the libraries for a build without internet, I guess it's all fine now 👍
