### ISSUE TITLE
Test executable doesn’t build in version 3

### ISSUE THREAD

**Issue by vitekcerny** [zlib-ng/minizip-ng#560]
Hi, I’m using minizip for simple decompression of zip file on windows. My build configuration is as follows: `cmake -B build -A Win32 -D MZ_COMPAT=OFF -D MZ_BZIP2=OFF -D MZ_LZMA=OFF -D MZ_ZSTD=OFF -D MZ_PKCRYPT=OFF -D MZ_WZAES=OFF -D MZ_SIGNING=OFF -D MZ_ICONV=OFF -D MZ_DECOMPRESS_ONLY=ON -D MZ_BUILD_TESTS=ON`
And I build using: `cmake --build build --config Release --parallel`

This was working fine previously, but starting with version 3 I get several link errors of unresolved external symbol _mz_crypt_xxx. A workaround is to enable signing by simply remove the flag `-D MZ_SIGNING=OFF`. This seems to work but I still think that signing support should be optional.

**Comment by nmoinvaz** [comment]
Should be fixed in `dev`. Thanks for reporting.

**Comment by vitekcerny** [comment]
Thank you!
