### ISSUE TITLE
can't unzip docx's emf file

### ISSUE THREAD

**Issue by wzwangyike** [zlib-ng/minizip-ng#581]
when i use minizip to unzip docx, and get emf file.

```c++
BYTE *ReadCurrentFile(unzFile uz, unsigned int &size)
{
	unz_file_info64 file_info;
	int err = unzGetCurrentFileInfo64(uz, &file_info, NULL, 0, NULL, 0, NULL, 0);
	if (err != UNZ_OK)
	{
		printf("GetCurrentFileInfo fail");
		return NULL;
	}
	err = unzOpenCurrentFile(uz);
	if (err != UNZ_OK)
	{
		printf("OpenCurrentFile fail");
		return NULL;
	}
	BYTE *p = new BYTE[(uint32_t)file_info.uncompressed_size];
	err = unzReadCurrentFile(uz, p, (uint32_t)file_info.uncompressed_size);
	if (err < 0)
	{
		printf("ReadCurrentFile fail %d\n", err);
		delete[] p;
		return NULL;
	}
	size = (uint32_t)file_info.uncompressed_size;
	return p;
}
```
the unzReadCurrentFile return -5.
when i walk into minizip at debug.
```c++
int32_t mz_stream_raw_read(void *stream, void *buf, int32_t size) {
    mz_stream_raw *raw = (mz_stream_raw *)stream;
    int32_t bytes_to_read = size;
    int32_t read = 0;

    if (raw->max_total_in > 0) {
        if ((int64_t)bytes_to_read > (raw->max_total_in - raw->total_in))
            bytes_to_read = (int32_t)(raw->max_total_in - raw->total_in);
    }

    read = mz_stream_read(raw->stream.base, buf, bytes_to_read);

    if (read > 0) {
        raw->total_in += read;
        raw->total_out += read;
    }

    return read;
}
```
the max_total_in and total_in is all size of file.
then.. it cannot read anything.

**Comment by nmoinvaz** [comment]
Can you attach the file?

**Comment by wzwangyike** [comment]
> Can you attach the file?

em...it cannot upload attach, it will warring `is not included in the list` ???
i don't know how to fix it and upload.

i try read file by find files: like:

```c++
BYTE *ReadCurrentFile(unzFile uz, const char *pName, unsigned int &size)
{
	if (UNZ_OK != unzLocateFile(uz, pName, NULL))
	{
		printf("not find %s", pName);
		return NULL;
	}
	unz_file_info64 file_info;
	int err = unzGetCurrentFileInfo64(uz, &file_info, NULL, 0, NULL, 0, NULL, 0);
	if (err != UNZ_OK)
	{
		printf("GetCurrentFileInfo fail");
		return NULL;
	}
	err = unzOpenCurrentFile(uz);
	if (err != UNZ_OK)
	{
		printf("OpenCurrentFile fail");
		return NULL;
	}
	BYTE *p = new BYTE[(uint32_t)file_info.uncompressed_size];
	err = unzReadCurrentFile(uz, p, (uint32_t)file_info.uncompressed_size);
	if (err < 0)
	{
		printf("ReadCurrentFile fail %d\n", err);
		delete[] p;
		return NULL;
	}
	size = (uint32_t)file_info.uncompressed_size;
	return p;
}
```

you can try to download by baiduyunpan :
link: https://pan.baidu.com/s/1RH_soVugzpTSW3buHzUKrw password: y5w6

**Comment by nmoinvaz** [comment]
I cannot download from that site, it wants me to create a login and it is hard to read in english. Can you email to me on my profile?

**Comment by wzwangyike** [comment]
> I cannot download from that site, it wants me to create a login and it is hard to read in english. Can you email to me on my profile?

i sended email,  reply if you get it!

**Comment by nmoinvaz** [comment]
I have not gotten it. Not in my junk mail.

**Comment by wzwangyike** [comment]
em...do you get the attachment? i retry to send, file split with 6 files.

**Comment by nmoinvaz** [comment]
Yes I have thank you.

**Comment by wzwangyike** [comment]
> Yes I have thank you.

do you reproduce this issue?

**Comment by nmoinvaz** [comment]
I have not had an opportunity to investigate.

**Comment by wzwangyike** [comment]
> I have not had an opportunity to investigate.

em...do you reproduce this issue?

**Comment by nmoinvaz** [comment]
I am not able to reproduce. I think I need the zip and full source code example.

**Comment by wzwangyike** [comment]
i send the text code for you, get it tell me. thanks

**Comment by wzwangyike** [comment]
em...do you reproduce this issue? i send you code and docx file before..

**Comment by wzwangyike** [comment]
> I am not able to reproduce - `max_total_in` is 0 for me. I think I need your zip and full source code example.

it happend at image02.emf file. other file not emf is ok, all emf file cannot read.

**Comment by wzwangyike** [comment]
em....do you get my last code..by 7/16

**Comment by wzwangyike** [comment]
i find my code extern png file by  unzReadCurrentFile return 0. none buffer read.
