### ISSUE TITLE
LNK2019 error when using  minizip (as static library)

### ISSUE THREAD

**Issue by DragonGamesStudios** [zlib-ng/minizip-ng#589]
I'm getting the following LNK2019 error (and plenty of others), when I'm trying to use minizip (just the standard functions, mz_zip_entry_*, mz_zip_*, mz_stream_os_*)).

```
error LNK2019: unresolved external symbol __imp__CryptMsgClose@4 called in function _mz_crypt_sign_verify
```

Am I doing something wrong. Is there an  unlisted dependence?

**Comment by Nekto89** [comment]
It's listed here https://github.com/zlib-ng/minizip-ng/blob/bc93e4077b542a35e9c60f275d984fc7690163dd/CMakeLists.txt#L440

**Comment by DragonGamesStudios** [comment]
Isn't this a Windows library? If so, will minizip run on Linux/Mac OS?

**Comment by nmoinvaz** [comment]
It is cross-platform library for Windows, macOS, and Linux. It uses different cryptographic library depending on what is available on the platform. If you use CMake it will build the project and solution files for you.
