### ISSUE TITLE
issues/vulnerabilities from security scan

### ISSUE THREAD

**Issue by DanielPutsch** [zlib-ng/minizip-ng#601]
Dear Developer,

I had to run an automated security scan of your code. The result is listed below. Can you please check the issues?

Thanks a lot!

**Off By One Error:**

~~Location: mz_zip_rw.c 
Line: 1146  
Source: strncpy(directory, path, sizeof(directory)); 
RelevantPart: sizeof~~ (See #611)

**Improper Null Terminations:**

Location: mz_strm_os_posix.c 
Line: 107 
Source: int32_t read = (int32_t)fread(buf, 1, (size_t)size, posix - >handle); 
RelevantPart: buf

Location: mz_strm_wzaes.c 
Line: 124 
Source: memcpy(verify, kbuf + (2 * key_length), MZ_AES_PW_VERIFY_SIZE); 
RelevantPart: verify

Location: mz_strm_mem.c 
Line: 66 
Source: memcpy(new_buf, mem - >buffer, mem - >size);
RelevantPart: new_buf

~~Location: mz_os_posix.c 
Line: 174 
Source: strncpy(name, path, len + 1); 
RelevantPart: name~~ (See https://github.com/zlib-ng/minizip-ng/commit/fe36527157ff96226f5309a99c806475ee0b75d2)

Location: mz_strm.c 
Line: 285 
Source: memmove(buf, buf + read, find_size); 
RelevantPart: buf

~~Location: mz_zip_rw.c 
Line: 1146 
Source: strncpy(directory, path, sizeof(directory)); 
RelevantPart: directory~~ (See #611)

**Comment by nmoinvaz** [comment]
I accept pull requests. Thank you.

**Comment by nmoinvaz** [comment]
Only string ones have been fixed. If you require any other fixes, do pull request. Thanks.
