### ISSUE TITLE
Instructions for building with zlib-ng not working on Windows

### ISSUE THREAD

**Issue by triplef** [zlib-ng/minizip-ng#603]
According to the [Wiki documentation](https://github.com/zlib-ng/minizip-ng/blob/master/doc/README.md#zlib-configuration), building with zlib-ng requires specifying `ZLIB_REPOSITORY` and `ZLIB_TAG` with CMake. This does not seem to be working for me (tested on Windows with CMake 3.21.21080301-MSVC_2).

Instead the variables that need to be defined are `zlib_REPOSITORY` and `zlib_TAG`, because the "zlib" parameter passed to `clone_repo`, which is used to create these variable names, is lowercase:
https://github.com/zlib-ng/minizip-ng/blob/6cffc951851620e0fac1993be75e4713c334de03/CMakeLists.txt#L214

With this the library is fetched correctly. This should be fixed either in CMakeLists.txt or the Wiki.
```
-- Fetching zlib https://github.com/zlib-ng/zlib-ng 2.0.6
-- Using CMake version 3.21.21080301-MSVC_2
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 2.0.6
```

However, even when passing these arguments I’m getting the following error:

```
-- The following OPTIONAL packages have not been found:

 * ZLIB

-- Using CryptoAPI
CMake Error at CMakeLists.txt:733 (install):
  install TARGETS given target "zlibstatic" which is an alias.
```

**Comment by triplef** [comment]
#574 has some of the solution here.

The last error I got comes from `list(APPEND MINIZIP_DEP_PKG ZLIB)`. Changing `ZLIB` to `ZLIBNG` here makes it work.

**Comment by nmoinvaz** [comment]
This should be resolved now in `dev` branch. Please let me know if you have any more issues. Thank you.

**Comment by triplef** [comment]
Thank you!
