### ISSUE TITLE
Add check for double call into mz_crypt_sha_begin

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/minizip-ng#605]
> It is a public API and a client app may call mz_crypt_sha_begin twice. Then maybe mz_crypt_sha_set_algorithm should not change sha->algorithm after mz_crypt_sha_begin, otherwise mz_crypt_sha_reset will crash an app.

@sergio-nsk

**Comment by sergio-nsk** [comment]
👎🏼
