### ISSUE TITLE
Compression with mz_stream_write failed to create a valid zip archive

### ISSUE THREAD

**Issue by kasimok** [zlib-ng/minizip-ng#608]
Hi, I'm following the test cases in 'test.c' to do compression with minizip-ng's steam API. The compression worked, the file size got deflated. 
However, the unzip terminal command complaints the output file is not a valid zip file.
```
$ unzip Model.stl.deflate.zlib.zip
Archive:  Model.stl.deflate.zlib.zip
  End-of-central-directory signature not found. Either this file is not
  a zip file, or it constitutes one disk of a multi-part archive. In the
  latter case the central directory and zip file comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zip file directory in one of Model.stl.deflate.zlib.zip or
        Model.stl.deflate.zlib.zip.zip, and cannot find Model.stl.deflate.zlib.zip.ZIP, period.
```

Below is the code snippet.

```c
    void *out_stream = NULL;
    uint32_t crc32 = 0;
    char filename[120];
    
    int64_t total_in = 0;
    int64_t total_out = 0;
    
    uint8_t buf[UINT16_MAX];
    void *in_stream = NULL;
    void *deflate_stream = NULL;
    int32_t read = 0;
    
    
    /*create in stream for reading*/
    mz_stream_os_create(&in_stream);
    if(mz_stream_os_open(in_stream, SOURCE_FILE, MZ_OPEN_MODE_READ) == MZ_OK){
        while ((read = mz_stream_os_read(in_stream, buf, UINT16_MAX)) > 0) {
            crc32 = mz_crypt_crc32_update(crc32, (const uint8_t *)buf, read);
        }
        mz_stream_os_close(in_stream);
    }
    
    mz_stream_os_delete(&in_stream);
    
    if (read < 0)
    {
        printf("Failed to read %s\n", SOURCE_FILE);
        return MZ_OPEN_ERROR;
    }
    
    printf("%s crc: 0x%08x\n", SOURCE_FILE, crc32);

    
    mz_stream_os_create(&out_stream);
    
    snprintf(filename, sizeof(filename), "%s.deflate.%s.zip", SOURCE_FILE, method);

    if(mz_stream_open(out_stream, filename, MZ_OPEN_MODE_CREATE | MZ_OPEN_MODE_WRITE) == MZ_OK){
        create_compress(&deflate_stream);
        mz_stream_set_base(deflate_stream, out_stream);
        //open stream for writing
        mz_stream_open(deflate_stream, NULL, MZ_OPEN_MODE_WRITE);
        mz_stream_os_create(&in_stream);
        
        if(mz_stream_os_open(in_stream, SOURCE_FILE, MZ_OPEN_MODE_READ) == MZ_OK){
            while((read = mz_stream_os_read(in_stream, buf, UINT16_MAX)) > 0){
                mz_stream_write(deflate_stream, buf, read);
            }
            mz_stream_os_close(in_stream);
        }
        
        mz_stream_os_delete(&in_stream);
        
        mz_stream_close(deflate_stream);
        
        mz_stream_get_prop_int64(deflate_stream, MZ_STREAM_PROP_TOTAL_IN, &total_in);
        mz_stream_get_prop_int64(deflate_stream, MZ_STREAM_PROP_TOTAL_OUT, &total_out);
        
        mz_stream_delete(&deflate_stream);
        
        printf("%s compressed from %u to %u\n", filename, (uint32_t)total_in, (uint32_t)total_out);
        
        mz_stream_os_close(out_stream);
    }
    
    mz_stream_os_delete(&out_stream);
```

**Comment by nmoinvaz** [comment]
Were you able to solve the problem?

**Comment by kasimok** [comment]
> 

Hi, @nmoinvaz Yes, the stream API works, I was confused as there is little documentation on these streaming compression APIs. Finally, I worked it out. Your lib works perfectly. Thanks

**Comment by Aiosa** [comment]
I am also having the same issue: `End-of-central-directory signature not found` - seems like the result needs some final touches before it is a valid zip but I could not find anything in the docs...

**Comment by nmoinvaz** [comment]
Did you call mz_zip_close? 

I should probably note here that using a stream to compress to zlib or deflate is not the same as creating a zip file.

**Comment by Aiosa** [comment]
When I did, my server shut down with error 500. The example did not use it so I thought not calling is the correct way.

**Comment by Aiosa** [comment]
So I tried like so: and the error is still the same.

    for (...) {
      //...
      err = mz_zip_entry_close_raw(zip_handle, total_bytes_written, computed_crc32);
      //...
   }

    int32_t mem_stream_size = 0;
    mz_zip_close(zip_handle);
    mz_stream_mem_close(mem_stream); //tried with and without
    mz_stream_mem_get_buffer_length(mem_stream, &mem_stream_size);

    //... read and send zip data

    mz_zip_delete(&zip_handle);
    mz_stream_mem_delete(&mem_stream);

**Comment by nmoinvaz** [comment]
Can you post the relevant code to a gist?

**Comment by Aiosa** [comment]
Yes, thank you. https://gist.github.com/Aiosa/8b62a9bd92f6019fb83143b53d9dbd74

**Comment by Aiosa** [comment]
In the end, there were several problems with my code (partially because I have not been using C++ for over three years so I make a lot of silly mistakes):
 - reading the memory stream pointer directly instead of using the minizip API - don't forget: `mz_stream_mem_seek` rewind and 
`mz_stream_mem_read` read of `mz_stream_mem_get_buffer_length` length
   - the output was basically rubbish bytes, no wonder no tool could read that
 - not calling `mz_zip_close` (missing in the wiki example, easy to overlook)
   - finalizes the zip and the central directory
 - some other mistake with writing the zip entry 'manually'
   - could not spot the mistake, solved issues above helped to extract the zip but the file inside was corrupted
   - fixed using a different API, instead of `mz_zip.h` functions I used writer from `mz_zip_rw.h` which is a bit simpler to use, binding the memory buffer to the writer instance: `mz_zip_writer_open(handle, mem_stream, 0)`
