### ISSUE TITLE
zlibng does not ship cmake config files

### ISSUE THREAD

**Issue by tpgxyz** [zlib-ng/minizip-ng#616]
Hi,

according to this commit 9184ba1216589077803b3e4e85f2b226f861ab2d a `find_dependency(ZLIBNG Required)` is added to minizip-config.cmake. Problem is zlib-ng does not ship any cmake config file, so when you are redistributing minizip-ng as a RPM you will get a broken dependencies on:
`Requires:  (cmake(zlibng) or cmake(ZLIBNG))`
```

DEBUG util.py:621:  Error: 
DEBUG util.py:621:   Problem: conflicting requests
DEBUG util.py:621:    - nothing provides (cmake(zlibng) or cmake(ZLIBNG)) needed by lib64minizip-ng-devel-3.0.5-1.aarch64
DEBUG util.py:623:  (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
DEBUG util.py:774:  Child return code was: 1
```

**Comment by nmoinvaz** [comment]
Feel free to make a PR.

**Comment by nmoinvaz** [comment]
Where does it say it is required? I can't find that line in that commit.

**Comment by tpgxyz** [comment]
minizip genrates that file /usr/lib64/cmake/minizip/minizip-config.cmake which have` find_dependency(ZLIBNG REQUIRED)`
```
...
include(CMakeFindDependencyMacro)
find_dependency(ZLIBNG REQUIRED)
find_dependency(BZip2 REQUIRED)
...
```

This cmake dependency cannot be satisfied, because there is not FindZLIGNG.cmake (like for example /usr/share/cmake/Modules/FindZLIB.cmake)

When you are redistributing minizip-np as a RPM file you will get, because of cmake provides/requires generator:
```
[tpg@omv-rockpro64 OpenMandriva]$ rpm -qp lib64minizip-ng-devel-3.0.5-1-omv4050.aarch64.rpm --requires
(cmake(bzip2) or cmake(BZip2))
(cmake(iconv) or cmake(Iconv))
(cmake(liblzma) or cmake(LibLZMA))
(cmake(openssl) or cmake(OpenSSL))
(cmake(zlibng) or cmake(ZLIBNG))
/usr/bin/pkg-config
cmake(zstd)
cmake-filesystem(aarch-64)
lib64minizip-ng3 = 3.0.5-1
pkgconfig(zlib)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
rpmlib(RichDependencies) <= 4.12.0-1
```
There are two options to consider:
1. do not add ZLIBNG as dependency in minizip-config.cmake
2. add FindZLIBNG.cmake to zlib-ng

**Comment by tpgxyz** [comment]
If you will add minizip-ng as development dependency in your project that uses CMake then it will fail because minizip-config.cmake intoduced `find_dependency(ZLIBNG REQUIRED)` while nothing provides that file :)
RPM provides/requires generator uses same CMake behaviour. I'll try to help solve this issue with some PR.

**Comment by nmoinvaz** [comment]
We did add FindZLING to cmake directory but you are saying it must be in zlib-ng? Thanks for your help.

**Comment by tpgxyz** [comment]
I found the culprit. We at OpenMandriva have a patched rpm requires generator for cmake(), which is way too aggresive on finding requires. Sorry for the noise.
