### ISSUE TITLE
REQ: PPMd support

### ISSUE THREAD

**Issue by chmichael** [zlib-ng/minizip-ng#617]
Hello,
  Please add PPMd support!

**Comment by nmoinvaz** [comment]
That is not something I am interested in doing myself. I am open to contributions from others.

**Comment by chmichael** [comment]
I wish i could help but i'm Delphi developer. PPMd has very good compression on text files.

Thank you

**Comment by pmqs** [comment]
See https://github.com/zlib-ng/minizip-ng/pull/937 for a PPMd support.
