### ISSUE TITLE
Symlinks Don't Extract on MacOS

### ISSUE THREAD

**Issue by c42v** [zlib-ng/minizip-ng#620]
When unzipping an archive that contains symlinks and was created by a separate tool on MacOS, the mz_zip_reader_save_all function extracts the symlinks as files containing the path to the target rather than as symlinks to the target.

To reproduce this behavior, you can follow these steps:
1. Create a directory and add a text file to it, say "test.txt"
2. In that directory, create a symlink to the text file via `ln -s test.txt link_to_test`
3. Compress the directory using `zip --symlinks -r dir_name dir_name.zip`
4. Use mz_zip_reader to extract the zip file. The resulting directory will not contain symbolic links. However, other tools, such as `zip` or Archive Utility will extract the symlinks correctly.

Here's a minimal snippet for step 4:
```
void * hdl;
mz_zip_reader_create(&hdl);
mz_zip_reader_open_file(hdl, "/path/to/dir_name.zip");
mz_zip_reader_save_all(hdl, "/path/to/extracted_dir_name");
```

This behavior was observed in version 3.0.5 on MacOS 12.3. Am I missing a flag on the reader by any chance? It does seem to work properly if the archive is created by an mz_zip_writer with the store_links flag set.

**Comment by nmoinvaz** [comment]
This is now fixed in `develop` branch.
