### ISSUE TITLE
Decompression cutting file with NUL characters before the end of file

### ISSUE THREAD

**Issue by ru842** [zlib-ng/minizip-ng#628]
I have been using minizip to compress and decompress different types of files and they all work fine except whenever there is a NUL character in the content of the file. 
The error comes when using the function: mz_zip_reader_entry_save_buffer(handle, buff, len);
When using this function the length of the file is read correctly but the buffer only contains the first couple of characters and its cut off by the first NUL character in the file and the rest of the file is ignored. 

![image](https://user-images.githubusercontent.com/105890174/169531440-bff19d54-a76c-47da-bd24-784b25cff426.png)

I am trying to decompress the file in memory. That is why I am trying to save it on a buffer.
I have decompressed it onto a file using the function:  mz_zip_reader_save_all(reader, destination.c_str());
Using this other function I am able to get the whole contents of the file even past the NUL characters.

Is there any way to use the mz_zip_reader_entry_save_buffer() or any similar function to decompress a file into a buffer including the NUL characters?

**Comment by nmoinvaz** [comment]
Are you opening the file in binary mode?

**Comment by nmoinvaz** [comment]
You have to provide your source code to know what is going on.

**Comment by ru842** [comment]
`	
	mz_zip_file *file_info = NULL;
	int32_t err = MZ_OK;
	char szBuff[256];
	int flag = 0;

	err = mz_zip_reader_goto_first_entry(handle);
	if (err == MZ_END_OF_LIST)
		return err;

	try
	{
		err = mz_zip_reader_entry_get_info(handle, &file_info);
		if (err != MZ_OK)
		{
			sprintf(szBuff, "Error getting entry info in archive. Reason code = 0x%hX", err);
			//throw exception
		}

		do
		{
			if (strcmp(file_info->filename, filename.c_str()) == 0)
			{
				len = mz_zip_reader_entry_save_buffer_length(handle);
				char *buff = (char *)malloc(len * sizeof(char));

				/* Save file to memory */
				err = mz_zip_reader_entry_save_buffer(handle, buff, len);

				if (err == MZ_OK)
				{
					err = mz_zip_reader_goto_next_entry(handle);
					if (err != MZ_OK && err != MZ_END_OF_LIST)
					{
						sprintf(szBuff, "Error going to next entry in archive = 0x%hX", err);
						//throw exception
					}
				}

				*buffer = buff;
				flag = 1;
			}
			else
			{
				mz_zip_reader_set_encoding(handle, MZ_ENCODING_UTF8);
				err = mz_zip_reader_goto_next_entry(handle);
				if (err != MZ_OK && err != MZ_END_OF_LIST)
				{
					sprintf(szBuff, "Error going to next entry in archive = 0x%hX", err);
					//throw exception
				}
			}
		} while (err == MZ_OK);


		if (flag != 1)
		{
			sprintf(szBuff, "File not found in archive. Reason code = 0x%hX", err);
			//throw exception
		}

		return err;
	}`

**Comment by ru842** [comment]
That is the code that was used, along with this setup:
`	minizip_opt opt;
	memset(&opt, 0, sizeof(opt));
	opt.compress_method = MZ_COMPRESS_METHOD_DEFLATE;
	opt.compress_level = MZ_COMPRESS_LEVEL_DEFAULT;
	opt.aes = MZ_AES_ENCRYPTION_MODE_256;
	opt.overwrite = true;
	opt.encoding = MZ_ENCODING_UTF8;`

**Comment by ru842** [comment]
I am not sure how to check if I am opening the file in binary. Could you walk me through that?

**Comment by ru842** [comment]
> Are you opening the file in binary mode?

@nmoinvaz what function is used for specifying binary mode when opening the file?

**Comment by ru842** [comment]
@nmoinvaz the issue persists after opening the file in binary mode. Could you help fix this?

**Comment by ru842** [comment]
The buffer in "mz_zip_reader_entry_save_buffer(handle, buff, len);" has only a couple characters despite it being able to recognize the length of the file is over 70000. This function is not populating the buffer as expected.

**Comment by nmoinvaz** [comment]
You will have to debug it on your end and figure out why.
