### ISSUE TITLE
Minizip decompression in buffer adding an extra new line character "\n" after each line

### ISSUE THREAD

**Issue by ru842** [zlib-ng/minizip-ng#629]
I am using the function mz_zip_reader_entry_save_buffer(handle, buff, len); to save a decompressed file into memory, putting it into a buffer to then use it, however if I put that buffer into a file, it adds a new line character "\n"  after every line when it already has a "\r", therefore creating a empty line between each row. Could you help me get this fixed?

If I print the buffer directly on the terminal it does not show the extra space, but when I open a notepad++ file you can see the extra space and the extra character.

![image](https://user-images.githubusercontent.com/105890174/170527127-780894b7-a9be-4b00-bc7d-a7c10ac93ca7.png)

______________________________________________________________________________________________________________________________________________
Here is a sample of the code I am using:

`mz_zip_file *file_info = NULL;
int32_t err = MZ_OK;
char szBuff[256];
int flag = 0;

err = mz_zip_reader_goto_first_entry(handle);
if (err == MZ_END_OF_LIST)
	return err;

try
{
	err = mz_zip_reader_entry_get_info(handle, &file_info);
	if (err != MZ_OK)
	{
		sprintf(szBuff, "Error getting entry info in archive. Reason code = 0x%hX", err);
		//throw exception
	}

	do
	{
		if (strcmp(file_info->filename, filename.c_str()) == 0)
		{
			len = mz_zip_reader_entry_save_buffer_length(handle);
			char *buff = (char *)malloc(len * sizeof(char));

			/* Save file to memory */
			err = mz_zip_reader_entry_save_buffer(handle, buff, len);

			if (err == MZ_OK)
			{
				err = mz_zip_reader_goto_next_entry(handle);
				if (err != MZ_OK && err != MZ_END_OF_LIST)
				{
					sprintf(szBuff, "Error going to next entry in archive = 0x%hX", err);
					//throw exception
				}
			}

			*buffer = buff;
			flag = 1;
		}
		else
		{
			mz_zip_reader_set_encoding(handle, MZ_ENCODING_UTF8);
			err = mz_zip_reader_goto_next_entry(handle);
			if (err != MZ_OK && err != MZ_END_OF_LIST)
			{
				sprintf(szBuff, "Error going to next entry in archive = 0x%hX", err);
				//throw exception
			}
		}
	} while (err == MZ_OK);

	if (flag != 1)
	{
		sprintf(szBuff, "File not found in archive. Reason code = 0x%hX", err);
		//throw exception
	}

	return err;
}`

**Comment by ru842** [comment]
@nmoinvaz  Could you guide me through how to do this?

**Comment by nmoinvaz** [comment]
Where is your code that writes to the file?

**Comment by ru842** [comment]
> Where is your code that writes to the file?

`fstream file;
			file.open("Test.txt", ios::out | ios::in);
			TS_TRACE(buffer);
			if (file.is_open())
			{
				file << buffer;
			}
			file.close();`

**Comment by nmoinvaz** [comment]
```
file.open("Test.txt", ios::out | ios::in | ios::binary);
```

**Comment by nmoinvaz** [comment]
![image](https://user-images.githubusercontent.com/1364432/170530395-58657230-423c-4ebf-bc29-23cb24356f71.png)

**Comment by nmoinvaz** [comment]
```
file.open("Test.txt", ios::out | ios::in | ios::binary | ios::trunc);
```
Both these questions are better for StackOverflow. There is no evidence either of these problems are related to minizip library.

**Comment by ru842** [comment]
@nmoinvaz thank you for your help, this seems to have solved the new line issue.
The decompression of a file with NUL characters is still failing even when opening the file in binary mode. 
I will mark this issue as solved and I would appreciate your help with the NUL character issue in the other inquiry.
