### ISSUE TITLE
it adds files with application's path in android 

### ISSUE THREAD

**Issue by mumin16** [zlib-ng/minizip-ng#630]
1.txt
xfolder
--2.txt

to zipped file:

/data/data/com.andorid.app/files/1.txt
/data/data/com.andorid.app/files/xfolder/2.txt

i want to my zipped file:

1.txt
xfolder
--2.txt

**Comment by mumin16** [comment]
i have 4 files: 1.txt , 2.txt,  3.txt in folder and 4.txt in folder:
when i zipped those files in desktop, i have zipped_in_desktop.zip. 
when i zipped those files in android, i have zipped_in_android.zip. 

https://github.com/mumin16/builds/tree/main

**Comment by nmoinvaz** [comment]
Need more info, such as how you are invoking the command. Perhaps you are not invoking it from the right directory. Maybe try to `cd /data/data/com.android.app/files/` first.
