### ISSUE TITLE
i need a ready-made compiled DLL file

### ISSUE THREAD

**Issue by mburaksaglik** [zlib-ng/minizip-ng#632]
Would you please share the win 32bit precompiled dll file for Lua 5.1. I have encountered an error many times when compiling VS2019 and Cmake, and I am very tired of doing this. I need that dll file now and I just couldn't do it.

[CMakeError.log](https://github.com/zlib-ng/minizip-ng/files/8829410/CMakeError.log)
[CMakeOutput.log](https://github.com/zlib-ng/minizip-ng/files/8829412/CMakeOutput.log)

**Comment by nmoinvaz** [comment]
No.
