### ISSUE TITLE
Building just-cloned minizip-ng fails

### ISSUE THREAD

**Issue by eleriaqueen** [zlib-ng/minizip-ng#633]
Hello, I just cloned the minizip-ng repo and hit 'configure' then 'build' in VSCode (with CMake 3.23.1) and the building process failed with the following errors:
![image](https://user-images.githubusercontent.com/4411178/172819807-11853e59-3e67-4af0-9193-c465febf6d9f.png)

Oh and I'm using this compiler:
![image](https://user-images.githubusercontent.com/4411178/172821227-78b301fb-967d-4457-a2cd-ce963fa1486f.png)

**Comment by nmoinvaz** [comment]
It is possible you are using an old version of Windows SDK?

**Comment by eleriaqueen** [comment]
SDK is the latest for Win10, but it doesn't seem like VSCode knows it's there... oh god... why is Microsoft so bad at making decent products especially when they need to communicate between each other. I mean I restarted my system in the hope it would make a difference but it did not.
I guess the issue must be on my end, not with your software, sorry for wasting your time.
