### ISSUE TITLE
Has a bug in minizip example ?

### ISSUE THREAD

**Issue by CaffeMrDe** [zlib-ng/minizip-ng#634]
The minizip-ng version is update to date. 
OS : linux centos 6.5 server  
zlib 1.2.8

There was a small bug or a problem with using controib/minizip . I compress a file with minizip execuate.  The  modification time   in zipfile is the same time.  

I can't  how to deal with this problem. what I should do to fix. Can you help me? Thanks.

**Comment by CaffeMrDe** [comment]
minizip-ng 3.0.6 - https://github.com/zlib-ng/minizip-ng
---------------------------------------------------
-l log1.zip 
      Packed     Unpacked Ratio Method   Attribs Date     Time  CRC-32     Name
      ------     -------- ----- ------   ------- ----     ----  ------     ----
         213        10320    2% deflate  81ff0080 02-28-97 05:09 988fc498   log1_20.LOG
         216        10320    2% deflate  81ff0080 02-28-97 05:09 bad40333   log1_21.LOG
         212        10320    2% deflate  81ff0080 02-28-97 05:09 ed466984   log1_22.LOG
         219        10320    2% deflate  81ff0080 02-28-97 05:09 7e415625   log1_23.LOG
         220        10320    2% deflate  81ff0080 02-28-97 05:09 66bc0273   log1_24.LOG
         245        10320    2% deflate  81ff0080 02-28-97 05:09 bb2c46f4   log1_00.LOG
         244        10320    2% deflate  81ff0080 02-28-97 05:09 6ac6797c   log1_01.LOG
         228        10320    2% deflate  81ff0080 02-28-97 05:09 464aede4   log1_02.LOG
         228        10320    2% deflate  81ff0080 02-28-97 05:09 55bedd16   log1_03.LOG
         230        10320    2% deflate  81ff0080 02-28-97 05:09 197dfcb2   log1_04.LOG
         231        10320    2% deflate  81ff0080 02-28-97 05:09 98b690d1   log1_05.LOG
         231        10320    2% deflate  81ff0080 02-28-97 05:09 d9ae9f5e   log1_06.LOG
         235        10320    2% deflate  81ff0080 02-28-97 05:09 79718a0b   log1_07.LOG
         234        10320    2% deflate  81ff0080 02-28-97 05:09 e8f04038   log1_08.LOG
         231        10320    2% deflate  81ff0080 02-28-97 05:09 4067ebad   log1_09.LOG
         237        10320    2% deflate  81ff0080 02-28-97 05:09 895b84b0   log1_10.LOG
         226        10320    2% deflate  81ff0080 02-28-97 05:09 751aa924   log1_11.LOG
         229        10320    2% deflate  81ff0080 02-28-97 05:09 d3ab9a53   log1_12.LOG
         235        10320    2% deflate  81ff0080 02-28-97 05:09 39e1efbe   log1_13.LOG
         224        10320    2% deflate  81ff0080 02-28-97 05:09 15182fe8   log1_14.LOG
         227        10320    2% deflate  81ff0080 02-28-97 05:09 464192d3   log1_15.LOG
         226        10320    2% deflate  81ff0080 02-28-97 05:09 c9d2adcc   log1_16.LOG
         233        10320    2% deflate  81ff0080 02-28-97 05:09 b3440706   log1_17.LOG
         235        10320    2% deflate  81ff0080 02-28-97 05:09 6e268c32   log1_18.LOG
         239        10320    2% deflate  81ff0080 02-28-97 05:09 823290f9   log1_19.LOG

**Comment by CaffeMrDe** [comment]
Oh， I find the problem and fix , please up add the code about it .

mz_zip_rw.c
```

int32_t mz_zip_writer_add_file(void *handle, const char *path, const char *filename_in_zip) { 
   ....
    mz_os_get_file_date(path, &file_info.modified_date, &file_info.accessed_date,
        &file_info.creation_date);

 // I add it to fix bug about modification bug, it work
    time_t ts;
    time(&ts);
    file_info.creation_date = ts;
    file_info.accessed_date = ts;
    file_info.modified_date = ts;

```

**Comment by nmoinvaz** [comment]
The source code is meant to just use the file's modified, accessed, and creation dates and store them in the zip. If you want to do what you are suggesting and use the current time you can modify the source code like you've done or you can use the linux `touch` command to modify the file's timestamp prior to adding it to the zip.
