### ISSUE TITLE
Handle leak in mz_os_open_dir in low memory situations

### ISSUE THREAD

**Issue by aallidina-cb** [zlib-ng/minizip-ng#640]
Thanks for maintaining this project. 

We ran minizip-ng against Coverity and found a few small issues. 

https://github.com/zlib-ng/minizip-ng/blob/47b8449fec2c7a575a506ecbe6399ad0603b5992/mz_os_win32.c#L402

In mz_os_win32.c::mz_os_open_dir(const char *path), the handle from FindFirstFileW gets leaked in low memory situations

```
    handle = FindFirstFileW(path_wide, &find_data);
    mz_os_unicode_string_delete(&path_wide);

    if (handle == INVALID_HANDLE_VALUE)
       // AA -> Should call FindClose(handle) before returning
        return NULL;

    dir_int = (DIR_int *)MZ_ALLOC(sizeof(DIR_int));
    if (dir_int == NULL)
        return NULL;
```

**Comment by nmoinvaz** [comment]
I think you mean FindClose on second if statement return. Please open PR.

**Comment by aallidina-cb** [comment]
Right, that's the one. OK, let me get to it.

**Comment by nmoinvaz** [comment]
Fixed in `develop` branch.
