### ISSUE TITLE
function return value question

### ISSUE THREAD

**Issue by xinmenghahaha** [zlib-ng/minizip-ng#649]
Why there is no return value judgement for function "mz_zip_reader_unzip_cd"  at the end of function “mz_zip_reader_open”  in the file of "https://github.com/zlib-ng/minizip-ng/blob/master/mz_zip_rw.c“(line 96) and just return MZ_OK? Is there any chance that the mz_zip_reader_unzip_cd could fail? Because I noticed that it could be failed under many cases and return unsuccessful code value.

**Comment by nmoinvaz** [comment]
It is only used if the zip file is compressing the central directory. Not every zip file will have that, so it ignored the return value and continues on as normal.

**Comment by xinmenghahaha** [comment]
您好，你的邮件我已收到，祝你有个好心情，谢谢~
