### ISSUE TITLE
minizip encrytion funcion test

### ISSUE THREAD

**Issue by caiqi1126** [zlib-ng/minizip-ng#650]
when we test the lattest minizip minizip openssl encrypt functions, we met the condition:

we can successfully add encrypt  the file "test.c" in result.zip by the following cmd:
./minizip "-t" "-o" "-z" "-h" "test.p12" "-w" "test" "result.zip" "test.c"

but, we can not encrypt the fold "fuzz" in result.zip by the following cmd:
 ./minizip "-t" "-o" "-z" "-h" "test.p12" "-w" "test" "result.zip" "test.c" "test.h" "empty.txt" "random.bin" "uniform.bin" "fuzz"

do you known way?

**Comment by nmoinvaz** [comment]
Please take a look at the `.github/workflow/build.yaml`, you will need to install the `test.p12` certificate as trusted on the system.

**Comment by nmoinvaz** [comment]
I have disabled `MZ_SIGNING` option by default on `develop` branch since there are extra testing requirements.
