### ISSUE TITLE
Support system copy of gtest

### ISSUE THREAD

**Issue by thesamesam** [zlib-ng/minizip-ng#654]
Please consider reworking d03ca72a2520d7ba55e8763d14aa0d70b960ba84 to allow using a system copy of gtest. Many package managers prohibit network access during the build.

While it may be possible to pre-download a copy and shove into the build dir, it's still a waste of resources and awkward to maintain.

Thanks!

**Comment by nmoinvaz** [comment]
It supports that already. If you have a parent project and already include Gtest then it will detect it.

**Comment by thesamesam** [comment]
I don't think that helps when gtest is just installed on the system though? At least it doesn't for me, and other CMake projects pick it up fine.

I don't think the target test will ever pass as we're not doing find_package (or anything else) for it.

**Comment by nmoinvaz** [comment]
Good idea. I am open to PRs.

**Comment by nmoinvaz** [comment]
Thanks for the fix.

**Comment by thesamesam** [comment]
No worries!
