### ISSUE TITLE
Compiling with WIN32_LEAN_AND_MEAN fails

### ISSUE THREAD

**Issue by tnixeu** [zlib-ng/minizip-ng#656]
I noticed that minizip-ng cannot be compiled with `WIN32_LEAN_AND_MEAN` defined.

When `WIN32_LEAN_AND_MEAN` is defined, then the header `winioctl.h` is not included by `windows.h`.

This header is needed for `FSCTL_GET_REPARSE_POINT` which is used here: https://github.com/zlib-ng/minizip-ng/blob/241428886216f0f0efd6926efcaaaa13794e51bd/mz_os_win32.c#L606

A solution could be to add the header `winioctl.h` after including `windows.h`.

I came across this problem because I compiled a bunch of libraries including minizip-ng with a CMake toolchain file set, which has `WIN32_LEAN_AND_MEAN` defined.

**Comment by nmoinvaz** [comment]
> A solution could be to add the header winioctl.h after including windows.h.

Sounds good. Please submit a PR.

**Comment by nmoinvaz** [comment]
Fixed in `develop`.
