### ISSUE TITLE
Split archive bug

### ISSUE THREAD

**Issue by mileta-r** [zlib-ng/minizip-ng#669]
When creating a split archive minizip on Windows10 machine creates thousands of empty files.
To reproduce unpack the attached file to a "SplitZipTest" folder and try to create a new archive with:
   minizip.exe -v -5 -k 200 SplitZip.zip path\to\SplitZipTest\\*
[SplitZip.zip](https://github.com/zlib-ng/minizip-ng/files/10551438/SplitZip.zip)

**Comment by nmoinvaz** [comment]
This should be resolved now in the `develop` branch. Thanks.
