### ISSUE TITLE
Zip buffers to in-memory stream

### ISSUE THREAD

**Issue by Aiosa** [zlib-ng/minizip-ng#670]
Hello, thanks for the lib! I want to use it to zip in-memory (image) byte streams to a single stream (for HTTP) - in CPP.

So far, I've built `libz-ng` globally from the source repo (which I did not use - I think - in the end), and compiled this lib:

      $  cmake -S . -B build -DMZ_COMPAT=OFF -DMZ_BZIP2=OFF -DMZ_LZMA=OFF -DMZ_ZSTD=OFF -DMZ_PKCRYPT=OFF \
            -DMZ_WZAES=OFF -DMZ_OPENSSL=OFF -DMZ_LIBBSD=OFF -DMZ_COMPRESS_ONLY=OFF \
            -DZLIB_REPOSITORY=https://github.com/zlib-ng/zlib-ng -DZLIB_TAG=develop -DMZ_FORCE_FETCH_LIBS=ON  \
            -DMZ_ZLIB=ON

Now, when I compile and run my test app
 
     $  g++ ziptest.cpp ziptest.hpp ../minizip-ng/libminizip-ng.a  -I../minizip-ng

I get        Zip entry open failure -1

How do I init the zip on a in-memory buffer, and read the result from it? I am getting stream error, I could not find anything in the docs.

    int32_t err = MZ_OK;
    void *zip_handle = NULL;
    mz_zip_create(&zip_handle);

    void *file_stream = NULL;
    mz_stream_os_create(&file_stream);

    err = mz_zip_open(zip_handle, file_stream, MZ_OPEN_MODE_WRITE);
    if (err != MZ_OK) {
        printf("Zip open failure %d\n", err);
        return err;
    }
    ...

Thank you.

**Comment by nmoinvaz** [comment]
The wiki might have what you are looking for https://github.com/zlib-ng/minizip-ng/wiki.

**Comment by Aiosa** [comment]
Love it, thank you. Did not expect to find this on Wiki, tried out almost everything else. Could be mentioned in some READMEs (which I thought serve as the only docs).

**Comment by TobyEalden** [comment]
> The wiki might have what you are looking for https://github.com/zlib-ng/minizip-ng/wiki.

Where has the wiki gone? This link just redirects to the main page.
