### ISSUE TITLE
lzma.h”: No such file or directory

### ISSUE THREAD

**Issue by JasonYANG170** [zlib-ng/minizip-ng#675]
C1083  “lzma.h”: No such file or directory	minizip	C:\Users\qw200\Downloads\minizip-ng-3.0.8\minizip-ng-3.0.8\mz_strm_lzma.c	15

**Comment by nmoinvaz** [comment]
Are you using CMake? You need to use it to setup the project and subprojects properly.

**Comment by sunshine-app** [comment]
add  include: C:\Strawberry\c\include
