### ISSUE TITLE
Create a zip file in memory?

### ISSUE THREAD

**Issue by dzenanz** [zlib-ng/minizip-ng#676]
How should I modify [`minizip_add` function](https://github.com/zlib-ng/minizip-ng/blob/cee6d8cbd4da70c48e9df1426607ff95b4f24fa6/minizip.c#L238-L286) to create an in-memory zip file?

I assume I should replace [mz_zip_writer_add_path](https://github.com/zlib-ng/minizip-ng/blob/cee6d8cbd4da70c48e9df1426607ff95b4f24fa6/minizip.c#L270) by [mz_zip_writer_add_buffer](https://github.com/zlib-ng/minizip-ng/blob/1593060ecf093411f1f20f655e50992913c6d5b9/doc/mz_zip_rw.md#mz_zip_writer_add_buffer), but `mz_zip_writer_open_file_in_memory` still requires a path.

By zip file in memory I mean a buffer with a pointer to the beginning and a length, which I could later write to a file named "something.zip", which would be a valid zip archive. Of course, the point of this is not to write it to disk but to transfer it to another library/upload/download.

**Comment by nmoinvaz** [comment]
Does this doc help? Use `mz_mem_stream..`
https://github.com/zlib-ng/minizip-ng/tree/develop/doc

**Comment by dzenanz** [comment]
That points me in the right direction. [`test_stream_mem()`](https://github.com/zlib-ng/minizip-ng/blob/8bba5e3fdfc4f8a6c6033cf2b7656cfb2779bef1/test/test.c#L304-L411) no longer exists in the repository. Perhaps it should be revived?

**Comment by dzenanz** [comment]
I just tried [test_stream_mem()](https://github.com/zlib-ng/minizip-ng/blob/8bba5e3fdfc4f8a6c6033cf2b7656cfb2779bef1/test/test.c#L304-L411), and it works. Encryption did not work properly in [my test](https://github.com/dzenanz/tensorstore/commit/d250bcad111989ffa9a7d64f9362b3df90f00f53), but that was probably due to weirdness of the [build system used](https://github.com/dzenanz/tensorstore/blob/d250bcad111989ffa9a7d64f9362b3df90f00f53/third_party/minizip_ng/minizip_ng.BUILD.bazel). Thanks for your help @nmoinvaz.
