### ISSUE TITLE
Incorrect handling of long odd length passwords

### ISSUE THREAD

**Issue by bajamircea** [zlib-ng/minizip-ng#678]
The fix for https://github.com/zlib-ng/minizip-ng/issues/523 (problem on Windows only with passwords that are 1 character in length) introduced an incompatibility with long passwords (over 64 chars) of odd length.

The fix introduced padding for odd length passwords with an extra byte set to 0. For longer passwords a hash is calculated which is different when the extra 0 is included.

Here a suggested patch (the additional test uses a password that is 65 chars long):
```diff --git a/mz_crypt_win32.c b/mz_crypt_win32.c
index bfc19a9..cf03e43 100644
--- a/mz_crypt_win32.c
+++ b/mz_crypt_win32.c
@@ -564,8 +564,8 @@ int32_t mz_crypt_hmac_init(void *handle, const void *key, int32_t key_length) {
         hmac->error = GetLastError();
         err = MZ_CRYPT_ERROR;
     } else {
-        /* Zero-pad odd key lengths */
-        if (key_length % 2 == 1)
+        /* Handle CryptImportKey single char password bug */
+        if (key_length == 1)
             key_length += 1;
         key_blob_size = sizeof(key_blob_header_s) + key_length;
         key_blob = (uint8_t *)MZ_ALLOC(key_blob_size);
diff --git a/test/test_crypt.cc b/test/test_crypt.cc
index 472e0d5..db78ba3 100644
--- a/test/test_crypt.cc
+++ b/test/test_crypt.cc
@@ -208,6 +208,7 @@ TEST(crypt, pbkdf2) {
     uint8_t key[MZ_HASH_SHA1_SIZE];
     char key_hex[256];
     const char *password = "passwordpasswordpasswordpassword";
+    const char *longpassword = "passwordpasswordpasswordpasswordpasswordpasswordpasswordpasswordp";
     const char *salt = "8F3472E4EA57F56E36F30246DC22C173";

     EXPECT_EQ(mz_crypt_pbkdf2((uint8_t *)password, (int32_t)strlen(password),
@@ -216,6 +217,13 @@ TEST(crypt, pbkdf2) {
     convert_buffer_to_hex_string(key, sizeof(key), key_hex, sizeof(key_hex));

     EXPECT_STREQ(key_hex, "852c7b71a104aaa8d8996c840c3d4d5d0db780aa");
+
+    EXPECT_EQ(mz_crypt_pbkdf2((uint8_t *)longpassword, (int32_t)strlen(longpassword),
+        (uint8_t *)salt, (int32_t)strlen(salt), iteration_count, key, sizeof(key)), MZ_OK);
+
+    convert_buffer_to_hex_string(key, sizeof(key), key_hex, sizeof(key_hex));
+
+    EXPECT_STREQ(key_hex, "b3e0b5ece77332506972e97b63b3a0a6d36c39a9");
 }
 #endif
 #endif
```

**Comment by nmoinvaz** [comment]
Can you great a PR?

**Comment by bajamircea** [comment]
Hei, I created https://github.com/zlib-ng/minizip-ng/pull/680

I also added a test for when the password is 1 char long.

FYI, I've tested the expected results against a python library e.g.
```
print(PBKDF2("passwordpasswordpasswordpasswordpasswordpasswordpasswordpasswordp", "8F3472E4EA57F56E36F30246DC22C173").hexread(20))
```
Thanks

**Comment by bajamircea** [comment]
It occurred to me that the PR is against the master branch, do you want me to make a PR against the develop branch instead?

**Comment by nmoinvaz** [comment]
Can you add a unit test also for the key `"helloworld"` with HMAC SHA1? According to my previous bug report, https://developercommunity.visualstudio.com/t/cryptimportkey-fails-to-import-plaintext-key-with/1215483 - it had failed with `ERROR_INVALID_PARAMETER.

**Comment by bajamircea** [comment]
Raised PR https://github.com/zlib-ng/minizip-ng/pull/681 based on develop with extra test

**Comment by bajamircea** [comment]
The PR was merged in develop, closing this issue
