### ISSUE TITLE
This commit breaks compatibility with Windows 7

### ISSUE THREAD

**Issue by hsdk123** [zlib-ng/minizip-ng#692]
https://github.com/zlib-ng/minizip-ng/commit/9829913018955aeb5f24acfd01eb79eaaaffa02f

This particular commit breaks compatibility for those who compile code on windows 8 and up, but want to maintain compatibility with Windows 7. `CreateFile2` is only available windows 8 and up.

**Comment by nmoinvaz** [comment]
All usages of `CreateFile2` check for Win8: 
```c
#if _WIN32_WINNT >= _WIN32_WINNT_WIN8
```
Perhaps your SDK doesn't have it defined

**Comment by hsdk123** [comment]
@nmoinvaz 
> v141_xp

With Windows 7 support having ended, I'm a little worried about the `_xp` option going away.

I've been compiling with `v143` for a while now on Windows 10, but have users that are on Windows 7. This commit breaks that since I compile on Windows 10, but they need Windows 7.

**Comment by nmoinvaz** [comment]
There should be another way to target XP with CMake, maybe CMAKE_SYSTEM_VERSION or something else. There is a reason why that if def is not being triggered. I don't plan on bringing that MZ_WINRT_API flag back, but I do accept PRs.

**Comment by hsdk123** [comment]
> There should be another way to target XP with CMake

I don't think it's really about cmake asking to target xp, at the end of the day it depends on what `_WIN32_WINNT ` is defined as, which I'm unsure is control-able by cmake.

If there is no intention to revert the commit, I'm sadly just going to have to break away from this repo.

**Comment by nmoinvaz** [comment]
The fact that you don't have _WIN32_WINNT set correctly means your app in general can pull in functions not meant for your target OS. 

You can try to set it directly during configure: -D _WIN32_WINNT=_WIN32_WINNT_XP.

**Comment by nmoinvaz** [comment]
> If there is no intention to revert the commit, I'm sadly just going to have to break away from this repo.

Why should I care?

**Comment by nmoinvaz** [comment]
> With Windows 7 support having ended, I'm a little worried about the _xp option going away.

This is not my problem, it's yours.

**Comment by hsdk123** [comment]
> Why should I care?
> This is not my problem, it's yours.

Indeed, you absolutely do not need to care.
