### ISSUE TITLE
Xcode warning: A function declaration without a prototype is deprecated in all versions of C and is not supported in C2x

### ISSUE THREAD

**Issue by computersmith64** [zlib-ng/minizip-ng#696]
I got this warning in two places when compiling recently (a Swift project in Xcode). The first was from this statement in zip.c:

local linkedlist_datablock_internal *allocate_new_datablock()

The warning went away when I changed it to: local linkedlist_datablock_internal *allocate_new_datablock(void)

The second warning is in mztools.c: extern int ZEXPORT unzRepair(file, fileOut, fileOutTmp, nRecovered, bytesRecovered)

I'm definitely no C/C++ expert, so I don't really know what I should do here.

**Comment by nmoinvaz** [comment]
What version is this for?

**Comment by nmoinvaz** [comment]
It seems like it is for the original minizip. Please report to the zlib library.
