### ISSUE TITLE
Install Destination for cmake-config files.

### ISSUE THREAD

**Issue by MehdiChinoune** [zlib-ng/minizip-ng#700]
Shouldn't cmake-config files be installed in a subdirectory of `lib/cmake` instead of the directory itself.
That was the case before 4.0.0, All the projects I deal with install their cmake-config in a subdirectory Is there a reason to install them directly on `lib/cmake`?

**Comment by nmoinvaz** [comment]
I don't know. I don't have much knowledge about packaging on Linux.

**Comment by MehdiChinoune** [comment]
A question?!
