### ISSUE TITLE
Different slashes

### ISSUE THREAD

**Issue by Evgeniy270** [zlib-ng/minizip-ng#701]
While create new archive with files (names used backslashes) created path with differebt slashes.
File "mz_zip.c" line 795 and below:

        while ((err == MZ_OK) && (backslash = strrchr(next, '\\')) != NULL) {
            int32_t part_length = (int32_t)(backslash - next);
            if (mz_stream_write(stream, next, part_length) != part_length ||
                mz_stream_write(stream, "/", 1) != 1) 
                err = MZ_WRITE_ERROR;

            left -= part_length + 1;
            next = backslash + 1;
        } 
This code replace backslashes to slashes. But this replace only last backslash. Right code want use "strchr", not "strrchr":

        while ((err == MZ_OK) && (backslash = strchr(next, '\\')) != NULL) {

**Comment by nmoinvaz** [comment]
Thank you. It is now fixed in `develop` branch.
