### ISSUE TITLE
gcc 链接minizip库异常

### ISSUE THREAD

**Issue by jiletianzun2011** [zlib-ng/minizip-ng#707]
minizip库使用的是linux上pc自带gcc编译的，出现以下错误，麻烦给予解惑，谢谢

gcc main.c -I ./usr/local/include -L ./usr/local/lib  -lminizip -o main
/usr/bin/ld: ./usr/local/lib/libminizip.a(mz_strm_zlib.c.o): in function `mz_stream_zlib_open':
mz_strm_zlib.c:(.text+0xe8): undefined reference to `deflateInit2_'

**Comment by nmoinvaz** [comment]
I don't speak this language. Looks like you aren't linking to zlib properly. Sorry. Can't help more than that.
