### ISSUE TITLE
could not find CheckSourceCompiles 

### ISSUE THREAD

**Issue by cracy3m** [zlib-ng/minizip-ng#720]
I was use `CMake`(v3.14.7) to build `minizip-ng`(v4.0.0), error pop up like this when configure:
```
[cmake] CMake Error at minizip-ng/CMakeLists.txt:27 (include):
[cmake]   include could not find load file:
[cmake]     CheckSourceCompiles
```
I think it is because CMake which under version v3.19 do not have CheckSourceCompiles module, so I change `include(CheckSourceCompiles)` to `include(CheckCSourceCompiles)` and then error go away, Am I right to fix this error?

By the way, how can I use `zlib-ng` library(source code, already exists on local disk) to build `minizip-np`?

**Comment by nmoinvaz** [comment]
Thank you for the report, I have made the change in `develop`.
