### ISSUE TITLE
OpenSSL 1.0.2h  

### ISSUE THREAD

**Issue by Janskid** [zlib-ng/minizip-ng#727]
libminizip.a can not be link, many openssl errs appeared.
like:  in func"mz_crypt_init" ,"OPENSSL_init_crypto"not defined!

**Comment by NickBrighten** [comment]
Are you sure that you also imported the OpenSSL library to your code ???

Or that the OpenSSL library is compiled before minizip-ng is compiled ???

**Comment by Janskid** [comment]
thanks ，  i have solved the issue by replace openssl1.1.1.
