### ISSUE TITLE
Worst LZMA compression on best compression level

### ISSUE THREAD

**Issue by gix** [zlib-ng/minizip-ng#731]
Taken from `mz_stream_lzma_set_prop_int64`:

```c
    case MZ_STREAM_PROP_COMPRESS_LEVEL:
        if (value >= 9)
            lzma->preset = LZMA_PRESET_EXTREME;
        else
            lzma->preset = LZMA_PRESET_DEFAULT;
        break;
```

Reading the xz-utils docs for the presets, and looking through its code, `LZMA_PRESET_EXTREME` is an extra flag on top of the compression level. Using it on its own is equal to using a compression level of 0, making `MZ_COMPRESS_LEVEL_BEST` result in the worst compression (and the other levels not doing anything). The level should probably be passed through, without using `LZMA_PRESET_EXTREME` at all.

**Comment by nmoinvaz** [comment]
Please consider making a PR. I don't use it on a regular basis.

**Comment by nmoinvaz** [comment]
Merged into `develop`.
