### ISSUE TITLE
Filenames or file comments >= 65536 bytes are truncated

### ISSUE THREAD

**Issue by dfandrich** [zlib-ng/minizip-ng#736]
When adding a file to a ZIP archive or file comment whose name is >= 65536 bytes, it is truncated. A name equal to 65536 bytes exactly is stored as having an empty name.

These condition should result in an error, not the creation of a corrupted ZIP file.

The attached program will show this issue by creating a file with a name 65536 bytes long.

[badzip.c.txt](https://github.com/zlib-ng/minizip-ng/files/13059978/badzip.c.txt)

**Comment by Neustradamus** [comment]
To follow this ticket

**Comment by nmoinvaz** [comment]
It sounds like the library does not have a security issue. PRs are welcome.

**Comment by tbeu** [comment]
> PRs are welcome.

You asked for it -> #743,
