### ISSUE TITLE
Backwards compatibility issue with zip_fileinfo structure definition in mz_compat.h

### ISSUE THREAD

**Issue by ljavorsk** [zlib-ng/minizip-ng#749]
There is a non-compatible structure definition of `zip_fileinfo` in `mz_compat.h` header file:

The individual members are in changed order, which makes the build fail due to incorrect initialization.

Minizip-ng structure: https://github.com/zlib-ng/minizip-ng/blob/ef3ef9a4b8319b94d174d8911404a8b98d319ac7/mz_compat.h#L137

Madler zlib structure: https://github.com/madler/zlib/blob/643e17b7498d12ab8d15565662880579692f769d/contrib/minizip/zip.h#L107

**Comment by nmoinvaz** [comment]
Please feel free to submit a PR.

**Comment by Coeur** [comment]
That `unz_file_info` structure was like that since January 2012 (6d35b6b8845fae3d3cbde67bdad40e47e4623cf8).
To my eyes, this change is breaking 12 years of compatibility (January 2012 - December 2023).
