### ISSUE TITLE
Problem with "relocating" minizip

### ISSUE THREAD

**Issue by ottmar-zittlau** [zlib-ng/minizip-ng#757]
Hi,

I'm currently trying to update our internal Conan-package of minizip.
Previously, we were using v2.9.3 with zlib - I would like to upgrade to v4.0.4.

I can create the package, but I encounter a problem if I try to reuse it - my compiler complains that it can't find zlib, even though cmake's `find_package` is successful.
As far as I can see, the problem are hard-coded paths to the dependencies (in my case zlib) inside the generated cmake files.
E.g. if I compile and install minizip on my machine, I see the following lines inside `minizip.cmake` (in `/lib/cmake` in the install folder):

```
set_target_properties(MINIZIP::minizip PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/minizip;${_IMPORT_PREFIX}/include/minizip"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libz.so"
)
```
Here it uses the zlib that is installed on my machine. If I would package this and try to use it on a different machine, the path needs to be exactly the same, even though, `find_package` might locate it somewhere else.

I would expect that this can be solved by making cmake put the name of the target (probably just `zlib`) there instead of a fixed path.

Do you have a solution for this issue? I could give it a try to fix this, if you are interested.

Thanks and best regards
oz

**Comment by nmoinvaz** [comment]
I don't have enough experience with CMake and Linux integration and I am primarily a Windows developer. Feel free to submit a PR if you have a solution. I recommend taking a look at the original commit that made that change for insights into why it is the way it is.

**Comment by Nekto89** [comment]
@ottmar-zittlau in your specific case I would suggest using proper conan way if you are already using at as package manager. Conan should generate cmake files with your local paths in any environment. You could take version from CCI (https://github.com/conan-io/conan-center-index/tree/master/recipes/minizip-ng/all) and adjust it to your specific needs.

**Comment by ottmar-zittlau** [comment]
@Nekto89 Excellent - for whatever reason I was not aware that there is an official package. Thanks a lot!
