### ISSUE TITLE
MZ_VERSION_BUILD became an octal number in 3.0.0, that becomes invalid with certain version numbers

### ISSUE THREAD

**Issue by progician** [zlib-ng/minizip-ng#758]
I was using OCIO with minizip-ng 3.0.9, and it broke the compilation with this error message:

```
/path/to/OpenColorIO/src/OpenColorIO/OCIOZArchive.cpp:530:5: error: invalid digit '9' in octal constant
#if MZ_VERSION_BUILD >= 040000
    ^
/path/to/minizip-ng/include/mz.h:18:47: note: expanded from macro 'MZ_VERSION_BUILD'
#define MZ_VERSION_BUILD                (030009)
```

Looking at the history of the project, since the version bump to 3.0.0, the problem exists:

https://github.com/zlib-ng/minizip-ng/commit/6f17da582d2327c8cdc43622ddd31a185b6ef5fb

As you can see, the diff shows that the version number went from 21006 (decimal) to 030000 (octal) which is a net reduction of the version number in the first place because 030000 octal is 12288 in decimal.

Later, we see the use of 'a' for the digit 10, which suggests that the true number you want to generate is a hexadecimal number. Would you mind fixing your processes?

**Comment by nmoinvaz** [comment]
Thanks. I have added 0x prefix to it.

**Comment by progician** [comment]
Thanks, that was really, really quick 👍🏻

**Comment by opoplawski** [comment]
It seems like it could also have been changed to `30010` and `40004`.  If sticking with hex, it seems like a new release of 3.X with the hex version might be in order.
