### ISSUE TITLE
minizip-ng conflicts with minizip-compat of zlib

### ISSUE THREAD

**Issue by wynnfeng** [zlib-ng/minizip-ng#759]
we cannot both dnf install minizip-compat(belongs to zlib) and minizip-ng,because both provide /usr/lib64/libminizip.so.1
`Error: Transaction test error:
  file /usr/lib64/libminizip.so.1 from install of minizip-compat-1.2.13-3.ocs23.x86_64 conflicts with file from package minizip-ng-4.0.3-1.ocs23.x86_64`

so is this a feature that when minizip-ng update to 4.XX， we cannot both zlib and minizup-ng?

**Comment by nmoinvaz** [comment]
It must be a CMake issue, but I don't have a lot of experience with Linux installations.

**Comment by VVD** [comment]
https://github.com/zlib-ng/minizip-ng/blob/13b01a74a44108557e00c78ffac54e4fae7f8c7f/CMakeLists.txt#L616 is the cause.

**Comment by nmoinvaz** [comment]
What do you propose?

**Comment by VVD** [comment]
Remove line `set(SOVERSION "1")`?

**Comment by nmoinvaz** [comment]
Just compile with `-D MZ_COMPAT=OFF`
