### ISSUE TITLE
Unable to zip a file with password protection

### ISSUE THREAD

**Issue by AruneemaXD** [zlib-ng/minizip-ng#762]
Using this example from stackoverflow. [How to create a password protected ZIP file in Windows using C](https://stackoverflow.com/a/60708484)

`#include <stdint.h>
#include "mz.h"
#include "mz_os.h"
#include "mz_strm.h"
#include "mz_strm_buf.h"
#include "mz_strm_split.h"
#include "mz_zip.h"
#include "mz_zip_rw.h"
#include <stdio.h>

int main() {
    void *writer = NULL;
    int32_t err = MZ_OK;

    mz_zip_writer_create(&writer);
    mz_zip_writer_set_password(writer, "mypassword");
    mz_zip_writer_set_compress_method(writer, MZ_COMPRESS_METHOD_DEFLATE);
    mz_zip_writer_set_compress_level(writer, MZ_COMPRESS_LEVEL_DEFAULT);
    err = mz_zip_writer_open_file(writer, "output.zip", 0, 0);
    if (err != MZ_OK) {
        printf("Could not open zip file for writing.");
        return 1;
    }
    err = mz_zip_writer_add_path(writer, "text1.txt", NULL, 0, 0);
    if (err != MZ_OK) {
        printf("Failed to add file to the archive.");
        printf("%d", err);
    }
    mz_zip_writer_close(writer);
    mz_zip_writer_delete(&writer);
    return 0;
}`

Except I am using Linux (Ubuntu 20) and Minizip 2.8.7.2.
The error I am getting is -109 (MZ_SUPPORT_ERROR)

Could it be related to [readme additional info on password protection](https://github.com/zlib-ng/minizip-ng/issues/492)

**Comment by nmoinvaz** [comment]
First try a newer version of minizip and using cmake to compile from sources.

**Comment by Patrix9999** [comment]
Make sure that you have available one of the compression dependencies.  
In my case, i've been getting the same runtime error, because for some reason `zstd` wasn't get found by the cmake.

If you're using cmake, check if you're getting this output message:
```
"Compression not supported due to missing libraries"
```

If so, this means that no compression algorithm wasn't found by the cmake, hence the problem.
