### ISSUE TITLE
Seek to start of file

### ISSUE THREAD

**Issue by Igor-Palaguta** [zlib-ng/minizip-ng#765]
Is there any way to seek to start of current file.

Function `unzseek64` cannot help, as it only works if `compression_method == 0`

As a workaround to close current file and to open it again.
```
unzCloseCurrentFile(file)
unzOpenCurrentFile(file)
```

Thanks

**Comment by nmoinvaz** [comment]
No it is not possible with any version because it first has to be decompressed. If you want the compressed bits you have to use `unzOpenCurrentFile2` with `raw = 1`
