### ISSUE TITLE
Feature request: added data safety via optional FlushFileBuffers/fsync before close

### ISSUE THREAD

**Issue by jjYBdx4IL** [zlib-ng/minizip-ng#782]
I'm storing file content data using minizip-ng in zip files while maintaining a dataset of metadata inside an sqlite database.

To ensure data consistency, I'd like minizip-ng to call FlushFileBuffers/fsync after flushing its internal buffers and directly before closing the native zip file handle(s). 

https://learn.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-flushfilebuffers

Can we add that to the official code base? I'd prefer not having a fork just for that. Alternatively, there could also be a callback that's called just before the native file handle gets closed. Or an option to not close the handle so I can do it manually after calling the minizip-ng zip close function.

**Comment by nmoinvaz** [comment]
You can open a PR and I can review.

**Comment by jjYBdx4IL** [comment]
I did more research. At least on Windows it might be enough to open the file afterwards and flush the handle then.
