### ISSUE TITLE
Compatibility issue with zipOpenNewFileInZip64

### ISSUE THREAD

**Issue by cameronwhite** [zlib-ng/minizip-ng#787]
Related to #400, it seems that the signature of `zipOpenNewFileInZip_64()` is incorrect and should have been `zipOpenNewFileInZip64()` (without the underscore). I ran into this after investigating some compilation issues reported by a user on Fedora with minizip-ng (https://github.com/powertab/powertabeditor/issues/478)

For reference in the original minizip: https://github.com/madler/zlib/blob/develop/contrib/minizip/zip.h#L163
vs https://github.com/zlib-ng/minizip-ng/blob/develop/mz_compat.h#L177

**Comment by nmoinvaz** [comment]
I have added a shim for it. Thanks for reporting.
