### ISSUE TITLE
mz_zip_writer_set_certificate function definition removed from version 4.0.5

### ISSUE THREAD

**Issue by bhavyajn7599** [zlib-ng/minizip-ng#788]
Hi team, 
I am facing undefined symbol error when I am trying to use the minizip library for my project. From what I have searched I can see that mz_zip_writer_set_certificate is defined in mz_zip_rw.h but its definition is removed from file mz_zip_rw.c from 4.0.5 version onwards. Is it obseleted or some new API is added in place of this?
![image](https://github.com/zlib-ng/minizip-ng/assets/171550500/db70cae0-d23a-4c8a-93e0-3164881624c5)

**Comment by nmoinvaz** [comment]
https://github.com/zlib-ng/minizip-ng/issues/687
