### ISSUE TITLE
x86_64 macOS release build

### ISSUE THREAD

**Issue by electricbolt** [zlib-ng/minizip-ng#789]
Hi,

Wondering if you could, for the next release (e.g. 4.0.8), make the macOS release a universal binary containing both x86_64 and arm64 binaries? You can join the two binaries together using the following command:

lipo -create -output minizip x86_64/bin/minizip arm64/bin/minizip

Cheers.

**Comment by nmoinvaz** [comment]
Feel free to submit a PR for it.
