### ISSUE TITLE
MZ_OPENSSL is not enabled

### ISSUE THREAD

**Issue by bhavyajn7599** [zlib-ng/minizip-ng#801]
I am trying to compile minizip 4.0.7 with MZ_OPENSSL=ON on Windows but this feature is still disabled everytime.
I have added the path of my Openssl installation in the environment variable but still this is off. Any idea how can we enable this. Is there any specific variable name in which we have to set Openssl path?
![Uploading image.png…]()

**Comment by nmoinvaz** [comment]
In CMake configure you can try and pass the ` -D OPENSSL_ROOT_DIR=/usr/local/opt/openssl -D OPENSSL_INCLUDE_DIRS=/usr/local/opt/openssl/include -D OPENSSL_CRYPTO_LIBRARY=/usr/local/opt/openssl/lib/libcrypto.dylib -D OPENSSL_SSL_LIBRARY=/usr/local/opt/openssl/lib/libssl.dylib`
Other than that, it is not something I know and might be better asked in StackOverflow.
