### ISSUE TITLE
mz_zip_entry_write_open use of file_info, modified after writing

### ISSUE THREAD

**Issue by rombust** [zlib-ng/minizip-ng#828]
Looking at the function: mz_zip_entry_write_open

zip->file_info is copied near the start of the function
```
       memcpy(&zip->file_info, file_info, sizeof(mz_zip_file));
       mz_stream_write(zip->file_info_stream, file_info, sizeof(mz_zip_file));
```
But zip->file_info maybe modified later on
```

  if (!is_dir) {
        if (zip->data_descriptor)
            zip->file_info.flag |= MZ_ZIP_FLAG_DATA_DESCRIPTOR;
        if (password)
            zip->file_info.flag |= MZ_ZIP_FLAG_ENCRYPTED;
    }

```
Those familiar with the code base, is this okay ? I am unsure at the moment if file_info_stream requires these flags to match those pushed to mz_zip_entry_write_header?

**Comment by nmoinvaz** [comment]
Those two flags have alternative methods of configuration.

**Comment by rombust** [comment]
Thanks. I can see that now.
